import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';

import { FontClassNames } from './font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={FontClassNames}>
      <body className="flex w-screen h-screen overflow-hidden tracking-wider cursor-default">
        <div className="w-60 p-5 bg-zinc-100">
          <Link
            href="/"
            className="mb-2 text-2xl font-silk-screen font-bold tracking-tight">
            T1 Fan Page
          </Link>
          <Link href="/videos">
            <div>영상 모아보기</div>
          </Link>
          <Link href="/articles">
            <div>기사 모아보기</div>
          </Link>
          <Link href="/calendar">
            <div>캘린더</div>
          </Link>
        </div>
        <div className="w-[calc(100%-240px)] p-5">{children}</div>
      </body>
    </html>
  );
}
