import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import './globals.css';

const roboto = Roboto_Condensed({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} flex w-screen h-screen overflow-hidden tracking-wider cursor-default`}>
        <div className="w-60 p-5 bg-zinc-100">
          <div className="mb-2 text-2xl font-bold">T1 Fan Page</div>
          <div>영상 모아보기</div>
          <div>기사 모아보기</div>
          <div>캘린더</div>
        </div>
        <div className="w-[calc(100%-240px)] p-5">{children}</div>
      </body>
    </html>
  );
}
